/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type Body struct {

	// The title of the post. Note that this title is used for SEO and when rendering the post as a listing, but will not appear in the actual post—for that, the title must be specified in the content field as well. Titles longer than 100 characters will be ignored. In that case, a title will be synthesized from the first content in the post when it is published.
	Title string `json:"title,omitempty"`

	// The format of the \"content\" field. There are two valid values, \"html\", and \"markdown\"
	ContentFormat string `json:"contentFormat,omitempty"`

	// The body of the post, in a valid, semantic, HTML fragment, or Markdown. Further markups may be supported in the future. For a full list of accepted HTML tags, see here. If you want your title to appear on the post page, you must also include it as part of the post content.
	Content string `json:"content,omitempty"`

	// Tags to classify the post. Only the first three will be used. Tags longer than 25 characters will be ignored.
	Tags string `json:"tags,omitempty"`

	// The original home of this content, if it was originally published elsewhere.
	CanonicalUrl string `json:"canonicalUrl,omitempty"`

	// The status of the post. Valid values are “public”, “draft”, or “unlisted”. The default is “public”.
	PublishStatus string `json:"publishStatus,omitempty"`

	// The license of the post. Valid values are “all-rights-reserved”, “cc-40-by”, “cc-40-by-sa”, “cc-40-by-nd”, “cc-40-by-nc”, “cc-40-by-nc-nd”, “cc-40-by-nc-sa”, “cc-40-zero”, “public-domain”. The default is “all-rights-reserved”.
	License string `json:"license,omitempty"`
}
