/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type ContributorListData struct {

	// a list of contributor objects within a data envelope
	Data []InlineResponse2002Data `json:"data,omitempty"`
}
