/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type InlineResponse2002Data struct {

	// An ID for the publication. This can be lifted from response of publications above
	PublicationId string `json:"publicationId,omitempty"`

	// A user ID of the contributor.
	UserId string `json:"userId,omitempty"`

	// Role of the user identified by userId in the publication identified by publicationId. 'editor' or 'writer'
	Role string `json:"role,omitempty"`
}
