/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

// an image object within a data envelope
type InlineResponse2004Data struct {

	// The URL of the image.
	Url string `json:"url,omitempty"`

	// An MD5 hash of the image data.
	Md5 string `json:"md5,omitempty"`
}
