/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type Post struct {

	// A unique identifier for the post.
	Id string `json:"id,omitempty"`

	// The post’s title
	Title string `json:"title,omitempty"`

	// The userId of the post’s author
	AuthorId string `json:"authorId,omitempty"`

	// The post’s tags
	Tags string `json:"tags,omitempty"`

	// The URL of the post on Medium
	Url string `json:"url,omitempty"`

	// The canonical URL of the post. If canonicalUrl was not specified in the creation of the post, this field will not be present.
	CanonicalUrl string `json:"canonicalUrl,omitempty"`

	// The publish status of the post.
	PublishStatus string `json:"publishStatus,omitempty"`

	// The post’s published date. If created as a draft, this field will not be present.
	PublishedAt string `json:"publishedAt,omitempty"`

	// The license of the post.
	License string `json:"license,omitempty"`

	// The URL to the license of the post.
	LicenseUrl string `json:"licenseUrl,omitempty"`
}
