/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type Publication struct {

	// A unique identifier for the publication.
	Id string `json:"id,omitempty"`

	// The publication’s name on Medium.
	Name string `json:"name,omitempty"`

	// Short description of the publication
	Description string `json:"description,omitempty"`

	// The URL to the publication’s homepage
	Url string `json:"url,omitempty"`

	// The URL to the publication’s image/logo
	ImageUrl string `json:"imageUrl,omitempty"`
}
