/* 
 * Medium API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package medium

type User struct {

	// A unique identifier for the user.
	Id string `json:"id,omitempty"`

	// The user’s username on Medium.
	Username string `json:"username,omitempty"`

	// The user’s name on Medium.
	Name string `json:"name,omitempty"`

	// The URL to the user’s profile on Medium.
	Url string `json:"url,omitempty"`

	// The URL to the user’s avatar on Medium.
	ImageUrl string `json:"imageUrl,omitempty"`
}
